### model
model_name_or_path: open-thoughts/OpenThinker-32B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /home/richard/LLaMA-Factory/examples/deepspeed/ds_z3_offload_config.json

### dataset
dataset: openthinker_hermes_function_calling
template: qwen
cutoff_len: 16384
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
mask_history: true

### output
output_dir: saves/OpenThinker-32B-FC-SFT-bf16
logging_steps: 1
save_steps: 1000
plot_loss: true

### train
# global_batch_size: 96
per_device_train_batch_size: 1
gradient_accumulation_steps: 3
learning_rate: 1.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

## ray
# ray_run_name: OpenThinker-7B-Hermes-FunctionCalling
# ray_num_workers: 4  # number of GPUs to use
# resources_per_worker:
#   GPU: 1
# placement_strategy: PACK